package api

import (
	_ "embed"
	"net/http"
)

//go:embed swagger-ui.html
var swaggerHTML []byte

// openapiSpec is the OpenAPI / Swagger spec generated by swag from handler
// annotations. Regenerate via `just openapi` after changing any handler.
//
//go:embed openapi/swagger.yaml
var openapiSpec []byte

// DocsHandler serves the Swagger UI page.
func DocsHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write(swaggerHTML)
}

// SpecHandler serves the OpenAPI YAML spec.
func SpecHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/yaml; charset=utf-8")
	w.Header().Set("Access-Control-Allow-Origin", "*")
	_, _ = w.Write(openapiSpec)
}
