// Request DTOs and shared response envelopes used by the JSON API.
//
// Keeping these in a dedicated file makes the OpenAPI spec generated by swag
// reference named schemas instead of inline anonymous structs.
package api

// StatusResponse is the standard envelope for endpoints that return a simple
// `{"status": "ok"}` payload (logout, mark-read, etc.).
type StatusResponse struct {
	Status string `json:"status" example:"ok"`
}

// LoginRequest is the body for POST /api/login.
type LoginRequest struct {
	Username string `json:"username" example:"admin"`
	Password string `json:"password" example:"hunter2"`
}

// AthleteRequest is the body for POST /api/athletes and PUT /api/athletes/{id}.
type AthleteRequest struct {
	Name            string `json:"name" example:"Charlie"`
	Tier            string `json:"tier,omitempty" example:"foundational"`
	Notes           string `json:"notes,omitempty"`
	Goal            string `json:"goal,omitempty"`
	DateOfBirth     string `json:"date_of_birth,omitempty" example:"2014-05-12"`
	Grade           string `json:"grade,omitempty" example:"6th"`
	Gender          string `json:"gender,omitempty" example:"M"`
	TrackBodyWeight bool   `json:"track_body_weight,omitempty"`
}
