// Request DTOs and shared response envelopes used by the JSON API.
//
// Keeping these in a dedicated file makes the OpenAPI spec generated by swag
// reference named schemas instead of inline anonymous structs.
package api

// StatusResponse is the standard envelope for endpoints that return a simple
// `{"status": "ok"}` payload (logout, mark-read, etc.).
type StatusResponse struct {
	Status string `json:"status" example:"ok"`
}

// LoginRequest is the body for POST /api/login.
type LoginRequest struct {
	Username string `json:"username" example:"admin"`
	Password string `json:"password" example:"hunter2"`
}

// AthleteRequest is the body for POST /api/athletes and PUT /api/athletes/{id}.
type AthleteRequest struct {
	Name            string `json:"name" example:"Charlie"`
	Tier            string `json:"tier,omitempty" example:"foundational"`
	Notes           string `json:"notes,omitempty"`
	Goal            string `json:"goal,omitempty"`
	DateOfBirth     string `json:"date_of_birth,omitempty" example:"2014-05-12"`
	Grade           string `json:"grade,omitempty" example:"6th"`
	Gender          string `json:"gender,omitempty" example:"male"`
	TrackBodyWeight bool   `json:"track_body_weight,omitempty"`
}

// ExerciseRequest is the body for POST /api/exercises and PUT /api/exercises/{id}.
type ExerciseRequest struct {
	Name        string `json:"name" example:"Bench Press"`
	Tier        string `json:"tier,omitempty" example:"foundational"`
	FormNotes   string `json:"form_notes,omitempty"`
	DemoURL     string `json:"demo_url,omitempty"`
	RestSeconds int    `json:"rest_seconds,omitempty" example:"90"`
	Featured    bool   `json:"featured,omitempty"`
}

// WorkoutRequest is the body for POST /api/athletes/{id}/workouts.
type WorkoutRequest struct {
	Date  string `json:"date,omitempty" example:"2026-05-12" jsonschema:"Workout date, YYYY-MM-DD. Defaults to today in the user's timezone. One resistance workout per athlete per day."`
	Notes string `json:"notes,omitempty" jsonschema:"Optional free-text note for the workout."`
	// FromPrescription, when true, seeds the new workout with today's prescribed
	// sets (reps + target weights prefilled) so the athlete confirms or adjusts
	// the actuals while logging. Has no effect if no program is assigned today.
	FromPrescription bool `json:"from_prescription,omitempty" jsonschema:"When true, prefill the workout with today's prescribed sets. No effect if no program is assigned today."`
}

// WorkoutSetRequest is the body for POST /api/athletes/{id}/workouts/{workoutID}/sets.
type WorkoutSetRequest struct {
	ExerciseID int64   `json:"exercise_id" example:"42" jsonschema:"Exercise catalog id (resolve a name to an id with list_exercises)."`
	Reps       int     `json:"reps" example:"5" jsonschema:"Repetitions performed. For rep_type=seconds this is the hold in seconds; for distance it is the distance in yards."`
	Weight     float64 `json:"weight,omitempty" example:"135" jsonschema:"Load in the user's configured weight unit (lbs by default, kg if configured). Omit or 0 for bodyweight."`
	RPE        float64 `json:"rpe,omitempty" example:"7" jsonschema:"Rate of Perceived Exertion, 0-10 (0 = not recorded). Omit if not measured."`
	RepType    string  `json:"rep_type,omitempty" example:"reps" jsonschema:"One of: reps, each_side, seconds, distance. Defaults to reps."`
	Category   string  `json:"category,omitempty" example:"main" jsonschema:"One of: main, supplemental, accessory. Defaults to main."`
	Notes      string  `json:"notes,omitempty" jsonschema:"Optional free-text note for this set."`
}

// WorkoutSetUpdateRequest is the body for PUT /api/athletes/{id}/workouts/{workoutID}/sets/{setID}.
//
// Fields are pointers so that omitting one leaves the stored column UNCHANGED
// (nil = "leave as-is"). A full-row overwrite would let a partial update — e.g.
// changing only notes — silently wipe weight/RPE and corrupt the load/ACWR
// history. A non-nil weight/rpe of 0 explicitly clears that column; a non-nil
// empty notes clears the note.
type WorkoutSetUpdateRequest struct {
	Reps   *int     `json:"reps,omitempty" example:"5" jsonschema:"New repetition count. Omit to leave unchanged."`
	Weight *float64 `json:"weight,omitempty" example:"135" jsonschema:"New load in the user's configured weight unit (lbs by default). Omit to leave unchanged; send 0 to clear."`
	RPE    *float64 `json:"rpe,omitempty" example:"7" jsonschema:"New RPE, 0-10. Omit to leave unchanged; send 0 to clear."`
	Notes  *string  `json:"notes,omitempty" jsonschema:"New note text. Omit to leave unchanged; send an empty string to clear."`
}

// WorkoutNotesRequest is the body for PUT /api/athletes/{id}/workouts/{workoutID}/notes.
type WorkoutNotesRequest struct {
	Notes string `json:"notes"`
}

// BodyWeightRequest is the body for POST /api/athletes/{id}/body-weights.
type BodyWeightRequest struct {
	Date   string  `json:"date,omitempty" example:"2026-05-12" jsonschema:"Measurement date, YYYY-MM-DD. Defaults to today in the user's timezone."`
	Weight float64 `json:"weight" example:"185.5" jsonschema:"Body weight in the user's configured unit (lbs by default, kg if configured)."`
	Notes  string  `json:"notes,omitempty" jsonschema:"Optional free-text note."`
}

// TrainingMaxRequest is the body for POST /api/athletes/{id}/training-maxes.
type TrainingMaxRequest struct {
	ExerciseID    int64   `json:"exercise_id" example:"42"`
	Weight        float64 `json:"weight" example:"315"`
	EffectiveDate string  `json:"effective_date,omitempty" example:"2026-05-12"`
	Notes         string  `json:"notes,omitempty"`
}

// ThrowingSessionRequest is the body for POST /api/athletes/{id}/throwing-sessions.
type ThrowingSessionRequest struct {
	Date       string   `json:"date,omitempty" example:"2026-05-12" jsonschema:"Session date, YYYY-MM-DD. Defaults to today in the user's timezone."`
	ThrowType  string   `json:"throw_type" example:"bullpen" jsonschema:"One of: bullpen, long_toss, plyo, game, flat_ground, pen, recovery, other."`
	ThrowCount *int64   `json:"throw_count,omitempty" example:"45" jsonschema:"Number of throws."`
	MaxIntent  *int64   `json:"max_intent,omitempty" example:"90" jsonschema:"Peak intent as a percent (0-100)."`
	Velocity   *float64 `json:"velocity,omitempty" example:"72.5" jsonschema:"Peak velocity in mph."`
	Fatigue    bool     `json:"fatigue,omitempty" jsonschema:"True if the athlete reported fatigue."`
	Pain       bool     `json:"pain,omitempty" jsonschema:"True if the athlete reported pain (Pitch Smart flag)."`
	Source     string   `json:"source,omitempty" example:"program" jsonschema:"Origin of the log, e.g. program or manual."`
	Team       string   `json:"team,omitempty" jsonschema:"Team the session was thrown for, if any."`
	Notes      string   `json:"notes,omitempty" jsonschema:"Optional free-text note."`
}

// SeasonPhaseRequest is the body for POST /api/athletes/{id}/season-phases.
type SeasonPhaseRequest struct {
	Sport     string `json:"sport,omitempty" example:"baseball"`
	Phase     string `json:"phase" example:"in"`
	StartDate string `json:"start_date" example:"2026-03-01"`
	EndDate   string `json:"end_date,omitempty" example:"2026-06-30"`
	Notes     string `json:"notes,omitempty"`
}

// BioSampleRequest is the body for POST /api/athletes/{id}/bio-samples.
type BioSampleRequest struct {
	RecordedAt string  `json:"recorded_at" example:"2026-05-12T07:30:00Z" jsonschema:"Timestamp the sample was taken, RFC3339 (e.g. 2026-05-12T07:30:00Z)."`
	Metric     string  `json:"metric" example:"resting_hr" jsonschema:"Metric key, e.g. resting_hr, hrv, weight, sleep_score."`
	Value      float64 `json:"value" example:"52" jsonschema:"Measured value, in the given unit."`
	Unit       string  `json:"unit,omitempty" example:"bpm" jsonschema:"Unit for value, e.g. bpm, ms, kg."`
	Source     string  `json:"source,omitempty" example:"manual" jsonschema:"Origin of the sample, e.g. manual, whoop, garmin."`
	Notes      string  `json:"notes,omitempty" jsonschema:"Optional free-text note."`
}

// ConditioningIntervalRequest is one work/rest effort within a conditioning session.
type ConditioningIntervalRequest struct {
	IntervalNumber int64    `json:"interval_number" example:"1"`
	WorkSeconds    *int64   `json:"work_seconds,omitempty" example:"90"`
	WorkDistance   *float64 `json:"work_distance,omitempty" example:"400"`
	RestSeconds    *int64   `json:"rest_seconds,omitempty" example:"60"`
	Notes          string   `json:"notes,omitempty"`
}

// ConditioningSessionRequest is the body for POST /api/athletes/{id}/conditioning-sessions.
type ConditioningSessionRequest struct {
	Date            string                        `json:"date,omitempty" example:"2026-05-12" jsonschema:"Session date, YYYY-MM-DD. Defaults to today in the user's timezone."`
	Modality        string                        `json:"modality" example:"run" jsonschema:"One of: run, bike, row, swim, ruck, other."`
	SessionType     string                        `json:"session_type" example:"interval" jsonschema:"One of: steady, interval, tempo, recovery, other."`
	TotalDistance   *float64                      `json:"total_distance,omitempty" example:"5000" jsonschema:"Total distance covered, in distance_unit."`
	DistanceUnit    string                        `json:"distance_unit,omitempty" example:"m" jsonschema:"Unit for total_distance, e.g. m, km, mi."`
	DurationSeconds *int64                        `json:"duration_seconds,omitempty" example:"1500" jsonschema:"Total duration in seconds."`
	AvgHR           *int64                        `json:"avg_hr,omitempty" example:"155" jsonschema:"Average heart rate in bpm."`
	RPE             *float64                      `json:"rpe,omitempty" example:"7" jsonschema:"Rate of Perceived Exertion, 0-10."`
	Notes           string                        `json:"notes,omitempty" jsonschema:"Optional free-text note."`
	Intervals       []ConditioningIntervalRequest `json:"intervals,omitempty" jsonschema:"Optional per-interval work/rest breakdown."`
}

// SkillSessionRequest is the body for POST /api/athletes/{id}/skill-sessions.
type SkillSessionRequest struct {
	Date            string   `json:"date,omitempty" example:"2026-05-12" jsonschema:"Session date, YYYY-MM-DD. Defaults to today in the user's timezone."`
	SkillType       string   `json:"skill_type" example:"batting" jsonschema:"One of: batting, fielding, pitching, agility, other."`
	RepCount        *int64   `json:"rep_count,omitempty" example:"50" jsonschema:"Number of repetitions performed."`
	LoadKg          *float64 `json:"load_kg,omitempty" example:"2" jsonschema:"Implement load in kilograms (this field is always kg, independent of the user's weight-unit preference)."`
	Velocity        *float64 `json:"velocity,omitempty" example:"68.5" jsonschema:"Peak velocity in mph."`
	DurationSeconds *int64   `json:"duration_seconds,omitempty" example:"1800" jsonschema:"Total duration in seconds."`
	Notes           string   `json:"notes,omitempty" jsonschema:"Optional free-text note."`
}

// RecoveryCheckinRequest is the body for POST /api/athletes/{id}/recovery-checkins.
type RecoveryCheckinRequest struct {
	Date       string   `json:"date,omitempty" example:"2026-05-12" jsonschema:"Check-in date, YYYY-MM-DD. Defaults to today in the user's timezone."`
	SleepHours *float64 `json:"sleep_hours,omitempty" example:"8.5" jsonschema:"Hours of sleep the prior night."`
	Soreness   *int64   `json:"soreness,omitempty" example:"3" jsonschema:"Muscle soreness on a 1-10 scale (1 = none, 10 = severe)."`
	Energy     *int64   `json:"energy,omitempty" example:"7" jsonschema:"Energy level on a 1-10 scale (1 = exhausted, 10 = fully energized)."`
	Notes      string   `json:"notes,omitempty" jsonschema:"Optional free-text note."`
}

// PreferencesRequest is the body for PUT /api/preferences.
type PreferencesRequest struct {
	WeightUnit string `json:"weight_unit,omitempty" example:"lbs"`
	Timezone   string `json:"timezone,omitempty" example:"America/New_York"`
	DateFormat string `json:"date_format,omitempty" example:"Jan 2, 2006"`
}

// EquipmentRequest is the body for POST /api/equipment and PUT /api/equipment/{id}.
type EquipmentRequest struct {
	Name        string `json:"name" example:"Squat Rack"`
	Description string `json:"description,omitempty"`
}

// AthleteEquipmentRequest is the body for POST /api/athletes/{id}/equipment.
type AthleteEquipmentRequest struct {
	EquipmentID int64 `json:"equipment_id" example:"5"`
}

// ExerciseEquipmentRequest is the body for POST /api/exercises/{id}/equipment.
type ExerciseEquipmentRequest struct {
	EquipmentID int64 `json:"equipment_id" example:"5"`
	Optional    bool  `json:"optional,omitempty"`
}

// AssignExerciseRequest is the body for POST /api/athletes/{id}/assignments
// and POST /api/athletes/{id}/assignments/reactivate.
type AssignExerciseRequest struct {
	ExerciseID int64 `json:"exercise_id" example:"42"`
	TargetReps int   `json:"target_reps,omitempty" example:"5"`
}

// ProgramTemplateRequest is the body for POST /api/programs.
type ProgramTemplateRequest struct {
	AthleteID   *int64 `json:"athlete_id,omitempty"`
	Name        string `json:"name" example:"5/3/1 BBB"`
	Description string `json:"description,omitempty"`
	NumWeeks    int    `json:"num_weeks" example:"3"`
	NumDays     int    `json:"num_days" example:"4"`
	IsLoop      bool   `json:"is_loop,omitempty"`
	Audience    string `json:"audience,omitempty" example:"adult"`
}

// ProgramTemplateUpdateRequest is the body for PUT /api/programs/{id}.
type ProgramTemplateUpdateRequest struct {
	Name        string `json:"name" example:"5/3/1 BBB"`
	Description string `json:"description,omitempty"`
	NumWeeks    int    `json:"num_weeks" example:"3"`
	NumDays     int    `json:"num_days" example:"4"`
	IsLoop      bool   `json:"is_loop,omitempty"`
}

// PrescribedSetRequest is the body for POST /api/programs/{id}/sets.
type PrescribedSetRequest struct {
	ExerciseID     int64    `json:"exercise_id" example:"42"`
	Week           int      `json:"week" example:"1"`
	Day            int      `json:"day" example:"1"`
	SetNumber      int      `json:"set_number" example:"1"`
	Reps           *int     `json:"reps,omitempty" example:"5"`
	Percentage     *float64 `json:"percentage,omitempty" example:"0.65"`
	AbsoluteWeight *float64 `json:"absolute_weight,omitempty"`
	SortOrder      int      `json:"sort_order,omitempty"`
	RepType        string   `json:"rep_type,omitempty" example:"reps"`
	Notes          string   `json:"notes,omitempty"`
}

// PrescribedSetUpdateRequest is the body for PUT /api/programs/{id}/sets/{setID}.
type PrescribedSetUpdateRequest struct {
	ExerciseID     int64    `json:"exercise_id" example:"42"`
	SetNumber      int      `json:"set_number" example:"1"`
	Reps           *int     `json:"reps,omitempty"`
	Percentage     *float64 `json:"percentage,omitempty"`
	AbsoluteWeight *float64 `json:"absolute_weight,omitempty"`
	SortOrder      int      `json:"sort_order,omitempty"`
	RepType        string   `json:"rep_type,omitempty"`
	Notes          string   `json:"notes,omitempty"`
}

// ProgressionRuleRequest is the body for POST /api/programs/{id}/rules.
type ProgressionRuleRequest struct {
	ExerciseID int64   `json:"exercise_id" example:"42"`
	Increment  float64 `json:"increment" example:"5"`
}

// CopyWeekRequest is the body for POST /api/programs/{id}/copy-week.
type CopyWeekRequest struct {
	SourceWeek int `json:"source_week" example:"1"`
	TargetWeek int `json:"target_week" example:"2"`
}

// AssignProgramRequest is the body for POST /api/athletes/{id}/programs.
type AssignProgramRequest struct {
	TemplateID int64  `json:"template_id" example:"7"`
	StartDate  string `json:"start_date" example:"2026-05-12"`
	Notes      string `json:"notes,omitempty"`
	Goal       string `json:"goal,omitempty"`
	Role       string `json:"role,omitempty" example:"primary"`
	Schedule   string `json:"schedule,omitempty"`
}

// AccessoryPlanRequest is the body for POST /api/athletes/{id}/accessories.
type AccessoryPlanRequest struct {
	Day          int     `json:"day" example:"1"`
	ExerciseID   int64   `json:"exercise_id" example:"42"`
	TargetSets   int     `json:"target_sets,omitempty" example:"3"`
	TargetRepMin int     `json:"target_rep_min,omitempty" example:"8"`
	TargetRepMax int     `json:"target_rep_max,omitempty" example:"12"`
	TargetWeight float64 `json:"target_weight,omitempty"`
	Notes        string  `json:"notes,omitempty"`
	SortOrder    int     `json:"sort_order,omitempty"`
}

// AccessoryPlanUpdateRequest is the body for PUT /api/athletes/{id}/accessories/{planID}.
type AccessoryPlanUpdateRequest struct {
	TargetSets   int     `json:"target_sets,omitempty"`
	TargetRepMin int     `json:"target_rep_min,omitempty"`
	TargetRepMax int     `json:"target_rep_max,omitempty"`
	TargetWeight float64 `json:"target_weight,omitempty"`
	Notes        string  `json:"notes,omitempty"`
	SortOrder    int     `json:"sort_order,omitempty"`
}

// AthleteNoteRequest is the body for POST /api/athletes/{id}/notes
// and PUT /api/athletes/{id}/notes/{noteID}.
type AthleteNoteRequest struct {
	Content   string `json:"content" jsonschema:"Note body text."`
	IsPrivate bool   `json:"is_private,omitempty" jsonschema:"When true, the note is visible only to coaches and admins, not the athlete."`
	Pinned    bool   `json:"pinned,omitempty" jsonschema:"When true, pin the note to the top of the journal."`
}

// GoalRequest is the body for PUT /api/athletes/{id}/goal.
type GoalRequest struct {
	Goal string `json:"goal"`
}

// TMBumpsRequest is the body for POST /api/athletes/{id}/cycle-review.
type TMBumpsRequest struct {
	Bumps []TMBump `json:"bumps"`
}

// TMBump is one entry in a TMBumpsRequest.
type TMBump struct {
	ExerciseID int64   `json:"exercise_id" example:"42"`
	NewWeight  float64 `json:"new_weight" example:"320"`
}

// BatchTMRequest is the body for POST /api/athletes/{id}/batch-tms.
type BatchTMRequest struct {
	Maxes []BatchTMEntry `json:"maxes"`
}

// BatchTMEntry is one entry in a BatchTMRequest.
type BatchTMEntry struct {
	ExerciseID int64   `json:"exercise_id" example:"42"`
	Weight     float64 `json:"weight" example:"315"`
}

// TrainingMaxNotesRequest is the body for PATCH /api/training-maxes/{tmID}/notes.
type TrainingMaxNotesRequest struct {
	Notes string `json:"notes"`
}

// LoginTokenRequest is the body for POST /api/users/{userID}/tokens.
type LoginTokenRequest struct {
	Label string `json:"label,omitempty"`
}

// ReviewRequest is the body for POST /api/athletes/{id}/workouts/{workoutID}/review.
type ReviewRequest struct {
	Status string `json:"status" example:"approved"`
	Notes  string `json:"notes,omitempty"`
}

// SettingUpdateRequest is the body for PUT /api/admin/settings.
type SettingUpdateRequest struct {
	Key   string `json:"key" example:"app.name"`
	Value string `json:"value" example:"My Custom Gym"`
}

// UserRequest is the body for POST /api/users.
type UserRequest struct {
	Username  string `json:"username" example:"alice"`
	Name      string `json:"name,omitempty"`
	Password  string `json:"password" example:"hunter22"`
	Email     string `json:"email,omitempty"`
	IsCoach   bool   `json:"is_coach,omitempty"`
	IsAdmin   bool   `json:"is_admin,omitempty"`
	AthleteID *int64 `json:"athlete_id,omitempty"`
}

// UserUpdateRequest is the body for PUT /api/users/{userID}.
type UserUpdateRequest struct {
	Username  string `json:"username" example:"alice"`
	Name      string `json:"name,omitempty"`
	Email     string `json:"email,omitempty"`
	Password  string `json:"password,omitempty"`
	IsCoach   bool   `json:"is_coach,omitempty"`
	IsAdmin   bool   `json:"is_admin,omitempty"`
	AthleteID *int64 `json:"athlete_id,omitempty"`
}

// MCPAccessRequest is the body for PUT /api/users/{userID}/mcp (HOF-004).
//
// Setting Enabled=true grants this user access to the parallel /api-mcp/*
// bearer route group on top of any valid JWT they present from the
// homelab-mcp OAuth AS. Flipping it back to false is the per-user
// revocation primitive — takes effect on the next request because the
// middleware reads users.mcp_enabled per call (no in-process cache).
type MCPAccessRequest struct {
	Enabled bool `json:"enabled"`
}

// NotificationPreferenceRequest is the body for PUT /api/notifications/preferences.
type NotificationPreferenceRequest struct {
	Type     string `json:"type" example:"workout_review"`
	InApp    bool   `json:"in_app"`
	External bool   `json:"external"`
}

// GenerateRequest is the body for POST /api/athletes/{id}/generate.
type GenerateRequest struct {
	ProgramName     string   `json:"program_name" example:"Sport Performance Block 4"`
	NumDays         int      `json:"num_days" example:"4"`
	NumWeeks        int      `json:"num_weeks" example:"3"`
	IsLoop          bool     `json:"is_loop,omitempty"`
	CoachDirections string   `json:"coach_directions,omitempty"`
	FocusAreas      []string `json:"focus_areas,omitempty"`
	ReferenceIDs    []int64  `json:"reference_ids,omitempty"`
}

// ImportExecuteRequest is the body for POST /api/athletes/{id}/import/execute.
type ImportExecuteRequest struct {
	Exercises []ImportMappingDecision `json:"exercises"`
}

// ImportMappingDecision is one mapping entry in an ImportExecuteRequest.
type ImportMappingDecision struct {
	Name     string `json:"name"`
	MappedID int64  `json:"mapped_id"`
	Create   bool   `json:"create"`
}

// CatalogImportExecuteRequest is the body for POST /api/catalog/import/execute.
type CatalogImportExecuteRequest struct {
	Exercises []CatalogImportMappingDecision `json:"exercises,omitempty"`
}

// CatalogImportMappingDecision is one mapping entry in a CatalogImportExecuteRequest.
type CatalogImportMappingDecision struct {
	MappedID int64 `json:"mapped_id"`
	Create   bool  `json:"create"`
}
